### ISSUE TITLE
Clean up WebAssembly Github organization's owners, teams, and committers

### ISSUE THREAD

**Issue by dschuff** [WebAssembly/meetings#1215]
The current structure of the WebAssembly GitHub organization dates back to a time long before the first version of the spec, before we established our current decision-making and proposal processes, and before we were even having regular meetings. As such there's not much rhyme or reason to it anymore, and there are a lot of people with very broad permissions (many of whom are no longer actively involved in WebAssembly), which in theory is a bit of a security risk. So I'm planning to clean up our teams and the permissions on our main repositories, and establish some kind of general principles going forward. The scope of these changes is only intended to be practical and administrative, and doesn't affect how we make decisions, advance proposals, etc so I'm hoping and expecting that it would be straightforward and uncontroversial.  Here's what I'm currently thinking: 

1. For redundancy, there should be several people who are Owners of the organization, who can grant permissions and take care of whatever is needed. Probably having the CG/WG chairs and spec editor is enough redundancy, and also covers North American and European timezones.

2. Anyone who has joined the CG can be a Member of the organization. Being a member allows you to be selected as a reviewer for PRs, easily @-mentioned in discussions, and a few other practical conveniences, but otherwise don't have any special permissions. We have 1521 registered members and I don't want to go through and add them all at once, but we'll add people on request (contact webassemly-cg-chair@chromium.org)

3. Proposal repos can be owned by the proposal champions, the spec repo can be owned by the spec editor, meetings by the CG and subgroup chairs, and the rest can just fall back to the chairs. Practically speaking, most of the repos already have active maintainers and not a lot of cruft, and don't actually need to change. 

4. Commit permissions on repositories can be given by a repository owner to any CG member based on a history of contributions and/or expectation of future contributions. Again, this is a practical consideration and not a special designation, so I think we can just say it's at the discretion of the owner.

5. Github Teams: We currently have a "Core" team which was originally created to distribute admin rights among all the browser vendors; a "Contributors" team which is never updated, and with no definition of what contribution means; and a "Workshop" team, with 56 members and write permissions on all the repos. I'm thinking we can just delete the Workshop and Core teams. I've heard there's a way to automatically populate a "contributors" team with folks who have had PRs accepted into repos, which might be a cool thing to have if we can set that up. But otherwise the teams shouldn't have any special designations or privileges.

6. People (even CG members) who aren't active for some amount of time (a year?) might get their write permissions revoked, but can always be added back later.

I'm opening this as an issue in case there is discussion or other ideas, I'm thinking it can be closed it by adding a document to https://github.com/WebAssembly/meetings/tree/main/process (and of course by actually implementing whatever we decide). Again, this is just about managing GitHub and not about the spec or decision-making.

**Comment by penzn** [comment]
> 5\. Github Teams: We currently have a "Core" team which was originally created to distribute admin rights among all the browser vendors; a "Contributors" team which is never updated, and with no definition of what contribution means; and a "Workshop" team, with 56 members and write permissions on all the repos. I'm thinking we can just delete the Workshop and Core teams. I've heard there's a way to automatically populate a "contributors" team with folks who have had PRs accepted into repos, which might be a cool thing to have if we can set that up. But otherwise the teams shouldn't have any special designations or privileges.

There might be some synergy between this item and fixing 'committers' language in consensus doc, it is similarly undefined.

https://github.com/WebAssembly/meetings/blob/bdbd2017eb75923c56fbbe48b43dd3d1afb5e5b7/process/consensus.md?plain=1#L129-L130

**Comment by dschuff** [comment]
Yes, definitely. The charter and consensus doc are the important parts. We can use Github to implement any policies that make sense (or not if it isn't useful).

**Comment by penzn** [comment]
After closer inspection the same doc actually defines committers, but in a somewhat odd way:

https://github.com/WebAssembly/meetings/blob/bdbd2017eb75923c56fbbe48b43dd3d1afb5e5b7/process/consensus.md?plain=1#L116-L123

IMO, the meaning of this passage is still vague. "Groups are free to decide" is not really an affirmative, and also which commit rights: any or specific important repos, like spec? For example all proposal champions have commit rights, but only to their respective repositories. And AFAIK we have never used this provision.

This seems to be some kind of W3C [boilerplate](https://github.com/search?q=org%3Aw3c%20committers&type=code), maybe that's why it says 'groups can define' instead of affirmatively stating that this group does it.

But since we are going to change commit rights, it would be a good idea to address this.

**Comment by conrad-watt** [comment]
> But since we are going to change commit rights, it would be a good idea to address this.

I think we should view this current PR as not interacting with the governance question, since we've never defined how our current use of the word "Committer" in the process relates to permissions in any WebAssembly org-related repo - this is exactly what we should fix in follow-on conversations. The options you sketch are (IMO) the sensible possible solutions.

I don't think anyone who can at this moment commit to a WebAssembly org repo should feel entitled to count themselves as a "Committer" wrt. the CG process. Even leaving aside our current unfortunate _lack_ of a definition for "Committer", GitHub seems to prefer the terms "contributor" and "write permissions" in its [official documentation](https://docs.github.com/en/organizations/managing-user-access-to-your-organizations-repositories/repository-roles-for-an-organization), and similarly our [current teams](https://github.com/orgs/WebAssembly/teams) don't identify "committers", only "contributors".

**Comment by conrad-watt** [comment]
To be extra clear, I'm advising: we should first commit this PR and enact the permissions clean up, then tackle the governance question. IMO delaying the clean-up to have the governance debate will make things more messy.

**Comment by dschuff** [comment]
As discussed and announced, I'm going to start working on this. If there are problems, please let me know (and if it's not clear from the PR what to do, let's fix that!)

**Comment by dschuff** [comment]
Just so I leave leave this on the record somewhere, I just updated the default repo permissions for members of the WebAssembly github org to "read" by default. This is mostly a no-op since the repos are all public, but it also means that any member of the org can now be added as a reviewer to any PR on any repo.
