### ISSUE TITLE
Wasm CG 03/28/2023 - Feedback and paths forward

### ISSUE THREAD

**Issue by syrusakbary** [WebAssembly/meetings#1248]
I just read the meeting notes of the latest Wasm CG in March 28th, 2023 : https://github.com/WebAssembly/meetings/blob/main/main/2023/CG-03-28.md

And to be honest, I'm alarmed by it for different reasons:
1. There was no proper preparation or introduction of the discussion, so myself and other people could chime in right then instead of learning of this after the fact. To be fair to everyone, [a PR was merged few days before the meeting introducing the new topic](https://github.com/WebAssembly/meetings/pull/1245/files), but I personally think "Phases doc clarifications" doesn't reflect properly the importance of the topic
2. A PR was opened introducing the concept of "production engines" https://github.com/WebAssembly/meetings/commit/9d1332d5e1dc61a21a4ed323f5ce84d0d99addb8#diff-3b8b7f1397be8a8b96fa23b77e71f968e98e4e18553de93f855ff51f811386a5R77, without actually specifying what is a production engine (it can't and shouldn't be subjective, it should be objective and measurable)
3. It opens the path of monopolization by bytecode alliance-related entities that might not reflect properly the browser and user needs. One of the things that balanced perfectly great Wasm and the JS API in general is the duality of different forces trying to make standards together. We can't and shouldn't move away from this. Even working in a server-side Wasm runtime, I reckon its quite important to get agreement from most of the web browsers on improvements on the Wasm spec. Otherwise things like the Component Model, might be forced upon instead of agreed upon.

For the reasons explained here I will like to talk in the next Wasm CG about this so we can discuss about this.

> Note: Based on this, and many other interactions, I personally think @lukewagner is no longer suited to be Chair of the Wasm CG due conflict of interests, but perhaps a discussion for other occasion.

To move forward productively, here are the points that I believe we *must* clearly define
* Is the Wasm CG in the business to decide what a "production engine" is?
   * In case it is, what makes an engine "production engine"? All the points must be defined and measured objectively so there is no subjective bias on the process
* Do all "production engines" weight the same? How do we weight on the decision if agreement is not reached (is the same that v8 and wasmtime disagree on something, that v8 and wasmer or JavascriptCore and wasmtime?)

Adding here the different people that were involved in the discussion to see if there are other things that will be important to cover:
@rossberg @tlively @conrad-watt @eqrion

**Comment by eqrion** [comment]
> 
>     2. A PR was opened introducing the concept of "production engines" [9d1332d#diff-3b8b7f1397be8a8b96fa23b77e71f968e98e4e18553de93f855ff51f811386a5R77](https://github.com/WebAssembly/meetings/commit/9d1332d5e1dc61a21a4ed323f5ce84d0d99addb8#diff-3b8b7f1397be8a8b96fa23b77e71f968e98e4e18553de93f855ff51f811386a5R77), without actually specifying what is a production engine (it can't and shouldn't be subjective, it should be objective and measurable)
> 

The change in that PR that refers to 'production engines' is:

```
During this phase, the following proceeds in parallel:

-   * Embedders implement the feature.
+   * Production engines implement the feature (where applicable).
```

As that's not an entry requirement to any phase, that change seems to me to be just wording of what usually happens during the phase. The phase 4 entry requirement is still that two Web VMs implement the feature. Changing that was discussed, but was intentionally not part of that commit so that there were no normative changes.

**Comment by dtig** [comment]
I understand the concern, and adding a few notes. In the meeting notes, @conrad-watt explicitly says (for which there was general agreement) that we should add an item for any edits to the process, and amending the process in any way to reflect the changing ecosystem for non-web engines should be explicitly called out so more interested folks can attend. 

The PR that was merged doesn't introduce any functional changes, it was clarifying existing processes. Specifically when an overview suffices, what spec tests should cover, and when the formal spec needs to be updated. The language still explicitly only has Web VMs in the process. While we value @lukewagner's input, @dschuff, @conrad-watt and myself are the co-chairs of the CG. 

Even if not accurately reflected in the notes, one of the bigger themes of the discussion was to introduce more flexibility in the standardization process to not be blocked on Web VMs, and about being inclusive of non-web engines in the future. I hope this helps clarify the discussion!

**Comment by syrusakbary** [comment]
Thanks for chiming in @dtig . 

Yes, I saw the comments from @conrad-watt, @dschuff and @tlively and I think they tried to balance properly the situation, although from reading the comments I didn't get the feeling that their comments were really taken in consideration (probably because I was not present and is hard to fully reflect the reactions via notes).

> While we value @lukewagner's input, @dschuff, @conrad-watt and myself are the [co-chairs of the CG](https://www.w3.org/community/webassembly/participants).

I think I confused the WebAssembly Community Group (Wasm CG) with the WebAssembly Working Group (Wasm WG), where Luke is actually the chair. In any case, thanks for the clarification.

> introduce more flexibility in the standardization process to not be blocked on Web VMs, and about being inclusive of non-web engines in the future

I actually see this as a healthy check. Right now Web Wasm VMs have a way bigger impact than non-web Wasm VMs. I see as a good thing that agreement on the web level needs to be reached first. Is a safe guard, a rail that keeps everything properly balanced.


-----

## How to move forward

To try to be also as productive as possible, I think is useful to analyze what was being commented, why I think we need to do better, and how I believe we can do it.

Here are some of the things that we can address:

> Even if not accurately reflected in the notes, one of the bigger themes of the discussion was [...]

The issue is that the notes might not reflect the full reality of the meeting. Not doing so can introduce some issues like lack of context or lack of understanding for people that were not in the meeting and have only the notes to see what happened.
**How to move forward from this?** I strongly think we should start recording the Wasm meetings, or have a AI-enabled realtime transcription of the meetings. (I believe Zoom is used, so both solutions should be easy implementable)

> CW: maybe this is too harsh of an opinion, but i’m not sure we want to work this out eagerly, maybe we should wait until there’s a proposal where this matters, and then we can figure how how we want to deal with it.
> AR: I would argue the exact opposite, we want to do that before it becomes controversial.

The response from @rossberg here is a big red flag. Things that are important, should be taken with importance.
**How to move forward from this?** It seems that people actually already know when things can become controversial. The cure for this is over-communication and discussion, not under-communication and eager discussion.

> TL: I don’t really want to be in the business of deciding which engine is production grade, and then we don’t have unanimous consent on when an engine count

Thomas is completely on point here. I personally think deciding what a "production engine" is is a slippery slope outside of the Web context.
**How to move forward from this?** If is decided that is on the Wasm CG to define what a "production engine" is, then is mandatory to define what that means, so runtimes can be measured objectively to assure no bias. Again, I would recommend against this as I perceive it a slippery slope.

> CW: my hot take is that we should be scared of relaxing the requirement because V8 has been running far enough ahead of the other web engines that we risk standardizing things that they don’t intend to implement.
> AR: Part of the motivation is to put more pressure on other engines if they fall behind. It’s not enough for V8 to run ahead, there still has to be a second production engine. Right now, outside of the web space, **wasmtime would be the one that qualifies**

Based on what, specifically? Are there first-class runtimes and second-class ones?
**How to move forward from this?** Define, specifically, what means a "production engine" outside of Web VMs, if that's the path that we want to take

---

Looking forward continuing the discussion in this issue and the next CG meeting

**Comment by rossberg** [comment]
@syrusakbary:
> Are there first-class runtimes and second-class ones?

Indeed, there are: right now, the three Web engines are first-class citizens with full privileges in the process, while all others are second-class. The point of the debate is to consider ways of refining this (increasingly outdated) definition with something more nuanced, to stay representative of the whole Wasm ecosystem. Details need to be carefully worked out and discussed, of course.

>>AR: I would argue the exact opposite, we want to do that before it becomes controversial.
>The response from @rossberg here is a big red flag. Things that are important, should be taken with importance.

The notes are a bit overcondensed here. What I was saying was that we should resolve this question before it becomes entangled with a discussion of a specific controversial feature. Somebody else put it better than me: "fix the roof while the sun is shining".

**Comment by conrad-watt** [comment]
@syrusakbary normally we would expect further discussions on GitHub before scheduling such an item for discussion in the CG. In particular, your misunderstanding occurred because we started speculatively talking about something _not_ scheduled or previously discussed on GItHub, after our scheduled business (the editorial process changes) had concluded.

IMO there are two short-term takeaways here.

1 - We shouldn't idly discuss potentially controversial issues in spare committee time. We should continue to be rigourous about beginning such discussions with a GitHub issue and scheduling committee items only once the discussion has concretised somewhat, and ideally once we have a few specific proposals contending for consensus.

2 - We should just remove "production" from the current process document - as @eqrion its current use is not normative. I'm happy to make a PR to this effect.

**Comment by conrad-watt** [comment]
@syrusakbary normally we would expect further discussions on GitHub before scheduling such an item for discussion in the CG. In particular, your misunderstanding occurred because we started speculatively talking about something _not_ scheduled or previously discussed on GItHub, after our scheduled business (the editorial process changes) had concluded.

IMO there are two short-term takeaways here.

1 - We shouldn't idly discuss potentially controversial issues in spare committee time. We should continue to be rigourous about beginning such discussions with a GitHub issue and scheduling committee items only once the discussion has concretised somewhat, and ideally once we have a few specific proposals contending for consensus.

2 - We should just remove "production" from the current process document - as @eqrion its current use is not normative. I'm happy to make a PR to this effect.

**Comment by syrusakbary** [comment]
> Indeed, there are: right now, the three Web engines are first-class citizens with full privileges in the process, while all others are second-class. The point of the debate is to consider ways of refining this (increasingly outdated) definition with something more nuanced, to stay representative of the whole Wasm ecosystem. Details need to be carefully worked out and discussed, of course.

From reading the WG transcription meeting, it seemed apparent that for you the first-class citizens were v8 and wasmtime and second-class citizens were the rest, not the browsers vs non-browsers VMs that you just mentioned, hence my comment.
In any case, as I also commented previously, I think having a web-first perspective has only positive side-effect in my opinion as deters the side effects of alliances buying seats of influence over the Wasm committee, as I believe is happening right now.

> The notes are a bit overcondensed here. What I was saying was that we should resolve this question before it becomes entangled with a discussion of a specific controversial feature. Somebody else put it better than me: "fix the roof while the sun is shining".

We really, really need to record the meetings. Not doing so can lead to many misunderstandings, as we have seen here.
I will attend the next WC meeting and make a proposal.

> We should continue to be rigourous about beginning such discussions with a GitHub issue and scheduling committee items only once the discussion has concretised somewhat, and ideally once we have a few specific proposals contending for consensus

300% agree. This is something important to not take lightly as there are many side effects for each of this decisions.

> We should just remove "production" from the current process document - as @eqrion noted its current use is not normative. I'm happy to make a PR to this effect.

Ok.

**Comment by dcodeIO** [comment]
Heh, after rereading the notes, if there is anything I know for certain, then if Wasmtime becomes a first-class citizen, alongside V8, and SpiderMonkey kicked out for "blocking adoption" (?!?), ya'll can bury this "World-Wide Web standard" right away. That's not the beginning of something great, that's the bloodshed of the past formalized with this committee and its aspirations becoming redundant quicker than you can hit merge. Not that I wouldn't find that outcome unintentionally hilarious, but folks, seriously, perhaps be a little careful with what you wish for 🤣

**Comment by conrad-watt** [comment]
To be absolutely clear, @rossberg only brought up the possibility of _relaxing_ the phase 4 bar, which currently requires at least two _Web_ engine implementations. Even in this eventuality SpiderMonkey and other Web engines would still count towards our implementation requirements, and no one in the meeting suggested otherwise.

**Comment by tlively** [comment]
I will also add that there was virtually no agreement at the meeting about whether, when, or how we should relax the requirement. Nothing about the requirement will be changing in the near future, and no changes will be made at all without careful deliberation, discussion, and input from the community.

**Comment by dcodeIO** [comment]
Great, I'll go and tell the community that it will be just like last time when its input was taken with "careful deliberation"

**Comment by penzn** [comment]
I am embarrassed to be this person, but I wasn't looking at the slides when the section introducing 'production' was on the screen, that's why even though I spoke against it in the discussion I didn't realize it was part of the change 😄 Thanks @conrad-watt and @dtig for removing that.

Notes are quite abbreviated, we either need more note takers, or just record (stack subgroup has done that and it works magically). From memory, two things that came out of the meeting (aside from rewording non-controversial parts of the doc) is to start getting regular input from non-Web implementers and to discuss what should the acceptable Phase 4 implementations be.

Some considerations here, expanding on what I said in the meeting. To be clear, I am also against relaxing two Web VMs requirement.

One problem with accepting non-Web VMs is that we don't know where to set the bar. Browsers have numerous extensive test suites (which go way beyond WebAssembly) and they are very complex systems, so in a way we are piggy-backing on their product maturity and development effort to set the bar. There isn't a comparable way to look at non-browser implementations yet, in fact different non-Web implementations may even have very different use cases and application domain (say crypto vs more traditional server side).

The other problem is by relaxing this requirement  we are going to ask Web engines to implement something because non-web engines support it. For example if Web engines X and Y implement a feature and it gets standardized, then remaining engine Z also needs to implement it. On the other hand, if we allow (say) a crypto engine W instead of Y, then both Y and Z are effectively implementing something a because W has it. I am not sure that is convincing from the Web spec and browser development point of view.

We've been talking about mechanisms to support purely non-browser uses in the standard. It would make sense for such situations to have non-browser implementations, however we don't have a case for that just yet.

Another practical idea in my view, is to develop non-Web functionality as strictly backwards compatible with the Web (see [WinterCG](https://github.com/wintercg/admin/blob/main/charter.md) for example), though potentially with less restrictive semantics.

**Comment by conrad-watt** [comment]
> I am embarrassed to be this person, but I wasn't looking at the slides when the section introducing 'production' was on the screen, that's why even though I spoke against it in the discussion I didn't realize it was part of the change

Just to reassure, [as noted above](https://github.com/WebAssembly/meetings/issues/1248#issuecomment-1492379573), the use of the word "production" in that note didn't imply any normative change to the phase advancement process, or movement towards @rossberg's subsequent thoughts on relaxing the phase 4 requirement (which I, you, and others spoke against). Similarly, its removal doesn't imply any normative change to the phase advancement process - it's for clarify given the above concerns.

**Comment by eqrion** [comment]
> 1 - We shouldn't idly discuss potentially controversial issues in spare committee time. We should continue to be rigourous about beginning such discussions with a GitHub issue and scheduling committee items only once the discussion has concretised somewhat, and ideally once we have a few specific proposals contending for consensus.

@conrad-watt As someone who has missed meetings before due to conflicts, I think it's okay for controversial issues to be discussed in spare committee time as long as it's:
 1. Available through notes
 2. Clear that more discussion must be had elsewhere
 3. Enough relevant individuals are around to have an informed discussion
 4. Nothing binding may be decided. 

All of those things were present in this situation.

I am in favor of automatically transcribed notes or recordings though. I think that could help.

> From reading the [WG transcription meeting](https://github.com/WebAssembly/meetings/blob/main/main/2023/CG-03-28.md?plain=1#L102), it seemed apparent that for you the first-class citizens were v8 and wasmtime and second-class citizens were the rest, not the browsers vs non-browsers VMs that you just mentioned, hence my comment.

> Heh, after rereading the notes, if there is anything I know for certain, then if Wasmtime becomes a first-class citizen, alongside V8, and SpiderMonkey kicked out for "blocking adoption" (?!?),

@syrusakbary @dcodeIO I just want to reiterate this as someone representing SpiderMonkey that any notion that SpiderMonkey is marginalized or being conspired against in the wasm standards process is inaccurate. That's not how the discussion went, and I don't know how to read that from the notes either.

**Comment by dcodeIO** [comment]
I didn't claim this strawman.

> AR: Part of the motivation is to put more pressure on other engines if they fall behind. It’s not enough for V8 to run ahead, there still has to be a second production engine. Right now, outside of the web space, wasmtime would be the one that qualifies. And wasmtime isn’t running ahead, so this wouldn’t change the game. The other two web engines besides V8 are JSC Apple and Spidermonkey Firefox and both of them have not been particularly quick and have often been a blocker for adopting features.
> 
> RH: my question here is, in what cases have we been blockers? I see tail calls but are there other examples?

I put the above more sharply because I would neither agree that Wasmtime "would be the one that qualifies" (👋 Node, Wasmer) nor that SpiderMonkey has "often been a blocker", together somehow justifying a change to the "web engine requirement" that would ominously "put more pressure", whatever that implies. From my experience, SpiderMonkey is quick with implementing features, and mentioning it in an embedded clause is not my main point.

**Comment by eqrion** [comment]
> I didn't claim this strawman.
> 

You said:

> SpiderMonkey kicked out for "blocking adoption"

I believe saying that we may be kicked out of the process fits within 'marginalized or conspired against'.

**Comment by dcodeIO** [comment]
Kicked out of the requirements. Or "considered less important" if you prefer. I can offer an edit if you think that helps.

**Comment by conrad-watt** [comment]
Again, even entertaining all the hypotheticals that were brought up at the end of the meeting, there was never any suggestion that SpiderMonkey could be considered less important than any other Web implementation with respect to satisfying the phase 4 requirements - only that certain other non-Web implementations might one day be considered as having equal importance.

**Comment by dcodeIO** [comment]
I'd argue that the editor of this standard "entertaining all the hypotheticals that were brought up at the end of the meeting" for the quadrillionth time is not coincidence on repeat but points right at the mother of all problems this committee needs to address asap. Wasmtime's significance is merely a function of a sophisticated social media fabrication plus an overrepresentation of VC-backed nonsense in this committee. SpiderMonkey, or any other actual Web engine for that matter, or Node as the primary serverside engine, is hard relevant. The overdose of psyops around here has even managed by now that people representing Web engines argue against their best interest by now. And what are you even talking about when saying "non-Web implementations might one day be considered as having equal importance [as actual Web implementations]" in a World-Wide Web standard? This is ridiculous. The only reason that statement is unconsciously considered as a valid point is because perception of reality is completely off by now. Eventually, that incompatibility-is-the-new-hotness bubble will burst, and ya'll are well advised to not sacrifice the standard (!) for that nonsense just because a bunch of startups all-in on a dead end made you believe something that isn't real. I mean, it shouldn't even be necessary that I come back here after all this committee has done to me just to tell you what you should already know.

**Comment by eqrion** [comment]
I think the original misunderstanding about the 'production engine' language in the phase clarification PR has been cleared up. And as we don't have any concrete proposed change to the phase 4 requirements, I don't think further discussion in this issue is going to be productive.

**Comment by titzer** [comment]
>  The overdose of psyops around here has even managed by now that people representing Web engines argue against their best interest by now. 

We don't insult and accuse here. That's not our culture. If you'd like to participate it the discussion, please stick to technical points and assume participants in it are stating their genuine opinions and that what they advocate is what they think will bring about good for Wasm and our community. 

Comments asserting vast conspiracies of bad people hurt our culture and sow distrust. We don't do that here.

**Comment by dcodeIO** [comment]
\*shakes head* Nothing to see here, please disperse.

**Comment by conrad-watt** [comment]
I agree with @eqrion that this issue has run its course.

The question was raised as to how we should improve record-keeping in the meetings, and several participants here and elsewhere have expressed interest in transcription software, which we'll investigate further.

@dcodeIO please respect the W3C [CEPC](https://www.w3.org/Consortium/cepc/) and [communications policies](https://www.w3.org/community/about/process/#general-policies) when commenting on issues.
