### ISSUE TITLE
Process for joining the meetings

### ISSUE THREAD

**Issue by trusktr** [WebAssembly/meetings#766]
Hello, what's the process for joining the meetings?

So far I know we have to be (I think) members of https://www.w3.org/community/webassembly. What's next?

**Comment by dtig** [comment]
The meeting is open to attend for the members of the community group - once you have joined, please [send an email](mailto:webassembly-cg-chair@chromium.org) to be added to the calendar event. The meeting documents may unfortunately  be a little out of date, but this information can also be found in the [agenda documents](https://github.com/WebAssembly/meetings/tree/master/main/2021) for each of the meetings.

**Comment by brejoc** [comment]
@dtig Thanks for providing more information about how to join the meetings. But unfortunately the agenda documents are asking to fill out a [registration form](https://docs.google.com/forms/d/e/1FAIpQLSdpO6Lp2L_dZ2_oiDgzjKx7pb7s2YYHjeSIyfHWZZGSKoZKWQ/viewform?usp=sf_link). I was unable to do that, because I don't have the required permissions. Not sure if this is different for other people.

![image](https://user-images.githubusercontent.com/34246/136190870-285585c4-52bd-44fa-8101-e1512c7472ed.png)

**Comment by dtig** [comment]
@brejoc It's been some time since the last comment, but it does look like the form to attend the WASI meetings is accessible  now in a private window without needing permissions. Feel free to reopen this issue if you are still having issues.

**Comment by brejoc** [comment]
Yes, this is working now. Thanks a lot!
